import 'js/bootstrap.min';
import 'js/jquery.isotope';
import 'js/jquery.min';
import 'js/jquery.slicknav';
import 'js/jquery.sticky';
import 'js/jquery.visible';
import 'js/modernizr.custom';
import 'js/scripts';
import 'js/slimbox2';